services:
  # Servicio de Autenticación
  fastapi-auth:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: fastapi-auth
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./auth/app:/app/app
      - ./common:/app/common
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgresql/timon_petstore?options=-csearch_path%3Dusers,public
    depends_on:
      - postgresql

  # Servicio de Veterinaria
  fastapi-veterinaria:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: fastapi-veterinaria
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./veterinaria/app:/app/app
      - ./common:/app/common
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgresql/timon_petstore?options=-csearch_path%3Dveterinary,public
    depends_on:
      - postgresql

  # Servicio de Peluquería
  fastapi-peluqueria:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: fastapi-peluqueria
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./peluqueria/app:/app/app
      - ./common:/app/common
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgresql/timon_petstore?options=-csearch_path%3Dgrooming,public
    depends_on:
      - postgresql

  # Servicio de Tienda (Pet Shop)
  fastapi-petshop:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: fastapi-petshop
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./petshop/app:/app/app
      - ./common:/app/common
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgresql/timon_petstore?options=-csearch_path%3Dpetshop,public
    depends_on:
      - postgresql

  # Frontend React App
  react-app:
    build: ./react-app
    container_name: react-app
    volumes:
      - ./react-app/src:/app/src
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - fastapi-auth
      - fastapi-veterinaria
      - fastapi-peluqueria
      - fastapi-petshop

  # Base de Datos PostgreSQL
  postgresql:
    image: postgres:13
    container_name: postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timon_petstore # Base de datos principal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Broker de Mensajes Redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # Celery Worker para tareas asíncronas
  celery-worker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: celery-worker
    command: celery -A common.celery_app worker --loglevel=info --queues=veterinaria,petshop
    volumes:
      - ./veterinaria/app:/app/veterinaria/app
      - ./petshop/app:/app/petshop/app
      - ./common:/app/common
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@postgresql/timon_petstore?options=-csearch_path%3Dpublic
    depends_on:
      - redis
      - postgresql

  # Celery Flower para monitoreo (opcional)
  celery-flower:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: celery-flower
    command: celery -A common.celery_app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./common:/app/common
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker

volumes:
  postgres_data:
